services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    network_mode: "host"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - AUTH_CHATS=${AUTH_CHATS}
      - UPSTREAM_REPO=${UPSTREAM_REPO}
      - UPSTREAM_BRANCH=${UPSTREAM_BRANCH}
      - GDRIVE_FOLDER_ID=${GDRIVE_FOLDER_ID}
      - INDEX_URL=${INDEX_URL}
      - ACCOUNTS_ZIP_URL=${ACCOUNTS_ZIP_URL}
      - TOKEN_PICKLE_URL=${TOKEN_PICKLE_URL}
